fail_fast: false
default_language_version:
  python: python3.11

repos:
  # Conventional commit
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Generic checks
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
      #
      - id: check-yaml
        exclude: ^tests/
      - id: check-json
        exclude: ^tests/
      - id: check-xml
        exclude: ^tests/
      - id: check-toml
        exclude: ^tests/
